# ===============================
# ? JWT CONFIG (SECURE)
# ===============================
jwt.secret=MySuperSecureKey@12345678901234567890
jwt.expiration=3600000

# ===============================
# ? APP CONFIG
# ===============================
spring.application.name=ecommerce-backend

# ? remove hardcoded URL issue (PaymentController fix)
app.base-url=http://localhost:8080

# ? remove magic number (AuthService fix)
app.default-balance=10000

# ===============================
# ?? DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# ? OPTIONAL (GOOD PRACTICE)
# ===============================
spring.jpa.properties.hibernate.format_sql=true
server.port=8080